build site:
  image: node:14.16.0
  stage: build
  script:
    - cd docs
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist


deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY"
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - ls
    - ls docs/
    - ls docs/src/.vuepress
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -e "ssh -p 768" -rav --delete docs/src/.vuepress/dist gitlab@neo4jstg.edvantalabs.com:/home/gitlab/bin/